server:
  port: 9999
spring:
  application:
    name: greeting.caller
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3300/eureka/,http://localhost:3301/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:instance-9999